export const LIST_CHARACTER = 'LIST_CHARACTER';
export const LIST_CHARACTER_PENDING = 'LIST_CHARACTER_PENDING';
export const LIST_CHARACTER_SUCCESS = 'LIST_CHARACTER_SUCCESS';
export const LIST_CHARACTER_FAILURE = 'LIST_CHARACTER_FAILURE';